# Generated by Django 5.0.2 on 2024-02-25 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('food_category', models.IntegerField(choices=[(1, 'VEG'), (2, 'NONVEG'), (3, 'VEGAN')], default=1)),
                ('meal_category', models.IntegerField(choices=[(1, 'BREAKFAST'), (2, 'LUNCH'), (3, 'SNACKS'), (4, 'DINNER'), (5, 'ALL')], default=5)),
                ('calories', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('cooking_instruction', models.TextField()),
                ('food_url', models.URLField(max_length=500)),
                ('food_suggestions', models.TextField(blank=True)),
                ('egg_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('milk_products_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('fats_oil_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('spices_herbs_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('vegetables_fruits_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('meat_seafood_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('dry_fruits_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('cereals_pulses_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('sugar_products_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('other_products_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='food_images/')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_images', to='trainer.food')),
            ],
        ),
        migrations.CreateModel(
            name='PlatedDishImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plated_dish_images/')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plated_dish_images', to='trainer.food')),
            ],
        ),
    ]
